#!/usr/bin/env node
import{fileURLToPath as __fup}from'url';import{dirname as __dn}from'path';import{createRequire as __cr}from'module';const __filename=__fup(import.meta.url);const __dirname=__dn(__filename);const require=__cr(import.meta.url);
import{exec as j}from"child_process";import*as y from"http";import*as T from"readline";import*as i from"fs";import*as E from"os";import*as p from"path";var m={name:"wozcode",version:"0.2.4",description:"WozCode enhanced coding tools \u2014 smart search, batch editing, SQL introspection, and cost-optimized subagent delegation",homepage:"https://withwoz.com",type:"module",main:"dist/standalone/cli.js",bin:{wozcode:"./dist/standalone/cli.js"},scripts:{build:"tsc && chmod +x dist/standalone/cli.js","build:plugin":"tsc && node dist/plugin/build-plugin.js",dev:"tsx src/standalone/cli.ts",start:"node dist/standalone/cli.js",lint:"npx eslint src/",compile:"tsc --noEmit",format:"npx prettier --write 'src/**/*.{ts,js}'"},author:"Woz",license:"UNLICENSED",dependencies:{"@anthropic-ai/claude-agent-sdk":"~0.2.74","@anthropic-ai/sdk":"~0.78.0","@modelcontextprotocol/sdk":"^1.27.1","@pg-nano/pg-parser":"~16.1.5",commander:"~14.0.3",glob:"^13.0.6",postgres:"~3.4.7",typescript:"~5.9.2",yaml:"^2.8.3",zod:"^4.3.6"},devDependencies:{"@eslint/js":"~10.0.1","@types/node":"~25.5.0","@typescript-eslint/utils":"^8.57.2",esbuild:"^0.27.4",eslint:"~10.1.0",tsx:"~4.21.0","typescript-eslint":"^8.57.2"},engines:{node:">=20.10"}};var W="woz",Q=`/${W}:login`,O=m.version,h=".wozcode",C="config.json",S="auth.json";function _(){return p.join(E.homedir(),h)}function A(){return p.join(_(),C)}function g(){return p.join(_(),S)}function I(){let e=_();i.existsSync(e)||i.mkdirSync(e,{recursive:!0})}function l(){let e=A();try{let o=i.readFileSync(e,"utf8");return JSON.parse(o)}catch{return{}}}function N(e){I();let o=A();i.writeFileSync(o,JSON.stringify(e,null,2),"utf8")}function x(){let e=g();try{let o=i.readFileSync(e,"utf8");return JSON.parse(o)}catch{return}}function u(e){I();let o=g();i.writeFileSync(o,JSON.stringify(e,null,2),{encoding:"utf8",mode:384})}function w(){let e=g();try{i.unlinkSync(e)}catch{}}var L="https://builder.withwoz.com",v="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0",R="https://build.withwoz.com";function d(){let e=l();return{supabaseUrl:process.env.WOZCODE_SUPABASE_URL??e.supabaseUrl??L,supabaseAnonKey:process.env.WOZCODE_SUPABASE_ANON_KEY??e.supabaseAnonKey??v,appUrl:process.env.WOZCODE_APP_URL??e.appUrl??R}}var se=["WOZ","INTERNAL","KEY"].join("_");var re=1800*1e3;var F=600*1e3,J=60*1e3,P=process.stdin.isTTY??!1;async function k(e){if(e!=null)return $(e);let o=d(),t=49152+Math.floor(Math.random()*16384);console.log(`Starting WozCode authentication...
`);let{promise:n,shutdown:s}=Z(t),c=`${o.appUrl}/wozcode/auth?callback_port=${t}`;console.log(`Opening browser to: ${c}
`),B(c);let r=[n];P?(console.log("Waiting for browser callback..."),console.log(`Or paste your token below (from the token page in your browser):
`),r.push(G()),r.push(b(F))):(console.log(`Waiting for browser callback...
`),r.push(b(J)));let a=await Promise.race(r);if(s(),a!=null)return u(a),console.log(`
Authenticated as ${a.email}`),a;console.error(P?`
Authentication timed out.`:`
Authentication timed out. The browser callback did not receive a response.`)}async function D(){w(),console.log("Logged out of WozCode.")}async function U(){return x()}async function z(e,o){if(!o?.force){let t=new Date(e.expiresAt),n=new Date(Date.now()+300*1e3);if(t>n)return e}try{let t=d(),n=await fetch(`${t.supabaseUrl}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:{"Content-Type":"application/json",apikey:t.supabaseAnonKey},body:JSON.stringify({refresh_token:e.refreshToken})});if(!n.ok)return;let s=await n.json(),c={accessToken:s.access_token,refreshToken:s.refresh_token,expiresAt:new Date(s.expires_at*1e3).toISOString(),userId:s.user.id,email:s.user.email??e.email};return u(c),c}catch{return}}function Z(e){let o,t=new Promise(s=>{o=y.createServer((c,r)=>{if(r.setHeader("Access-Control-Allow-Origin","*"),r.setHeader("Access-Control-Allow-Methods","POST, OPTIONS"),r.setHeader("Access-Control-Allow-Headers","Content-Type"),c.method==="OPTIONS"){r.writeHead(204),r.end();return}if(c.method==="POST"&&c.url==="/callback"){let a="";c.on("data",f=>{a+=f.toString()}),c.on("end",()=>{try{let f=JSON.parse(a);r.writeHead(200,{"Content-Type":"application/json"}),r.end(JSON.stringify({ok:!0})),s(f)}catch{r.writeHead(400),r.end("Invalid JSON")}});return}r.writeHead(404),r.end()}),o.listen(e,"127.0.0.1")});function n(){o?.close()}return{promise:t,shutdown:n}}function G(){return new Promise(e=>{let o=T.createInterface({input:process.stdin}),t="";o.on("line",n=>{t+=n;try{let s=JSON.parse(t.trim());if(s.accessToken&&s.refreshToken){o.close(),e(s);return}}catch{}}),o.on("close",()=>{if(t.trim())try{let n=JSON.parse(t.trim());if(n.accessToken&&n.refreshToken){e(n);return}}catch{}e(void 0)})})}function b(e){return new Promise(o=>{setTimeout(()=>o(void 0),e)})}function H(e){if(typeof e!="object"||e==null)return!1;let o=e;return typeof o.accessToken=="string"&&typeof o.refreshToken=="string"&&typeof o.expiresAt=="string"&&typeof o.userId=="string"&&typeof o.email=="string"}function $(e){try{let o=JSON.parse(e);if(!H(o)){console.error("Invalid token JSON: missing required fields."),console.error("Required fields: accessToken, refreshToken, expiresAt, userId, email");return}return u(o),console.log(`
Authenticated as ${o.email}`),o}catch(o){console.error(`Failed to parse token JSON: ${o instanceof Error?o.message:String(o)}`);return}}function B(e){let o=process.platform==="darwin"?`open "${e}"`:process.platform==="win32"?`start "" "${e}"`:`xdg-open "${e}"`;j(o,t=>{t&&console.log(`Could not open browser. Visit this URL manually:
  ${e}
`)})}import{spawn as K}from"child_process";var V=process.argv[2];switch(V){case"login":{let e=process.argv.indexOf("--token"),o=e!==-1?process.argv[e+1]:void 0,t=await k(o);if(t!=null){let n=d(),s=l();s.supabaseUrl=n.supabaseUrl,s.supabaseAnonKey=n.supabaseAnonKey,s.appUrl=n.appUrl,N(s),console.log(`
Config saved to ~/.wozcode/config.json`)}process.exit(t!=null?0:1);break}case"logout":{await D(),process.exit(0);break}case"status":{let e=await U();if(e==null)console.log("Not logged in. Run `wozcode login` to authenticate.");else{let o=await z(e);if(o==null)console.log("Session expired. Run `wozcode login` to re-authenticate.");else{let t=new Date(o.expiresAt);console.log(`WozCode:      v${O}`),console.log(`Logged in as: ${o.email}`),console.log(`User ID:      ${o.userId}`),console.log(`Token expires: ${t.toLocaleString()}`);let n=l();n.supabaseUrl&&console.log(`Supabase:     ${n.supabaseUrl}`),n.appUrl&&console.log(`App URL:      ${n.appUrl}`)}}process.exit(0);break}default:{K("claude",["--agent","wozcode",...process.argv.slice(2)],{stdio:"inherit"}).on("exit",o=>process.exit(o??0));break}}
